### ISSUE TITLE
Get action fails when using docker image tag 0.7.0-rc.1

### ISSUE THREAD

**Issue by ostefano** [cf-platform-eng/concourse-pypi-resource#84]
Hi,

The GET action fails when using the docker image tagged 0.7.0-rc.1, which is supposed to be the most recent if we trust the push date (19 days ago). Note that everything works when using the image tagged 0.7.0 (which semantically should be the most recent, although it has been pushed more than 4 months ago.

Having said that, the error that pops up when using 0.7.0-rc.1 is:

```
Output directory: /tmp/build/get
Try 1 of 3 to call function `download_version` from module `pypi_resource.in_`
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/pipio.py", line 54, in run
    platform=options.platform,
AttributeError: 'Values' object has no attribute 'platform'
List Versions returned 2
Try 2 of 3 to call function `download_version` from module `pypi_resource.in_`
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/pipio.py", line 54, in run
    platform=options.platform,
AttributeError: 'Values' object has no attribute 'platform'
List Versions returned 2
Try 3 of 3 to call function `download_version` from module `pypi_resource.in_`
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/pipio.py", line 54, in run
    platform=options.platform,
AttributeError: 'Values' object has no attribute 'platform'
List Versions returned 2
-- Failed retrying after 3 tries with a 5.000000 second delay
Traceback (most recent call last):
  File "/opt/resource/in", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/in_.py", line 107, in main
    response = in_(destdir, sys.stdin)
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/in_.py", line 82, in in_
    response = download(resconfig, destdir)
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/retry.py", line 21, in wrapper
    raise e
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/retry.py", line 15, in wrapper
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pypi_resource/in_.py", line 58, in download_version
    raise ValueError("No matching packages found.")
ValueError: No matching packages found.
```

After some debugging I believe that the option arguments are not correctly parsed by `pip`, possibly because pip got updated in the meanwhile, and the assumptions on the underlying parser used by `Command in _internal/cli/base_command.py` are no longer valid.

**Comment by mboldt** [comment]
Thank you for your patience; I've blocked time tomorrow to investigate.
